services:


    net.telepay.exchange_provider:
        class: Telepay\FinancialApiBundle\DependencyInjection\TelepayExchangeProvider
        arguments:
            - "@net.telepay.exchanges.BTCtoEUR.v1"
            - "@net.telepay.exchanges.BTCtoPLN.v1"
            - "@net.telepay.exchanges.BTCtoFAC.v1"
            - "@net.telepay.exchanges.BTCtoUSD.v1"
            - "@net.telepay.exchanges.BTCtoMXN.v1"
            - "@net.telepay.exchanges.BTCtoFAIRP.v1"

            - "@net.telepay.exchanges.EURtoBTC.v1"
            - "@net.telepay.exchanges.EURtoPLN.v1"
            - "@net.telepay.exchanges.EURtoFAC.v1"
            - "@net.telepay.exchanges.EURtoUSD.v1"
            - "@net.telepay.exchanges.EURtoMXN.v1"
            - "@net.telepay.exchanges.EURtoFAIRP.v1"

            - "@net.telepay.exchanges.FACtoBTC.v1"
            - "@net.telepay.exchanges.FACtoPLN.v1"
            - "@net.telepay.exchanges.FACtoEUR.v1"
            - "@net.telepay.exchanges.FACtoUSD.v1"
            - "@net.telepay.exchanges.FACtoMXN.v1"
            - "@net.telepay.exchanges.FACtoFAIRP.v1"

            - "@net.telepay.exchanges.PLNtoBTC.v1"
            - "@net.telepay.exchanges.PLNtoFAC.v1"
            - "@net.telepay.exchanges.PLNtoEUR.v1"
            - "@net.telepay.exchanges.PLNtoUSD.v1"
            - "@net.telepay.exchanges.PLNtoMXN.v1"
            - "@net.telepay.exchanges.PLNtoFAIRP.v1"

            - "@net.telepay.exchanges.USDtoBTC.v1"
            - "@net.telepay.exchanges.USDtoFAC.v1"
            - "@net.telepay.exchanges.USDtoEUR.v1"
            - "@net.telepay.exchanges.USDtoPLN.v1"
            - "@net.telepay.exchanges.USDtoMXN.v1"
            - "@net.telepay.exchanges.USDtoFAIRP.v1"

            - "@net.telepay.exchanges.MXNtoBTC.v1"
            - "@net.telepay.exchanges.MXNtoFAC.v1"
            - "@net.telepay.exchanges.MXNtoEUR.v1"
            - "@net.telepay.exchanges.MXNtoPLN.v1"
            - "@net.telepay.exchanges.MXNtoUSD.v1"
            - "@net.telepay.exchanges.MXNtoFAIRP.v1"

            - "@net.telepay.exchanges.FAIRPtoBTC.v1"
            - "@net.telepay.exchanges.FAIRPtoFAC.v1"
            - "@net.telepay.exchanges.FAIRPtoEUR.v1"
            - "@net.telepay.exchanges.FAIRPtoPLN.v1"
            - "@net.telepay.exchanges.FAIRPtoUSD.v1"
            - "@net.telepay.exchanges.FAIRPtoMXN.v1"


    net.telepay.exchanges.BTCtoEUR.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "BTC"
            - "EUR"
            - "BTCtoEUR"

    net.telepay.exchanges.BTCtoPLN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "BTC"
            - "PLN"
            - "BTCtoPLN"

    net.telepay.exchanges.BTCtoFAC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "BTC"
            - "FAC"
            - "BTCtoFAC"

    net.telepay.exchanges.BTCtoUSD.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "BTC"
            - "USD"
            - "BTCtoUSD"

    net.telepay.exchanges.BTCtoMXN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "BTC"
            - "MXN"
            - "BTCtoMXN"

    net.telepay.exchanges.BTCtoFAIRP.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "BTC"
            - "FAIRP"
            - "BTCtoFAIRP"



    net.telepay.exchanges.EURtoBTC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "EUR"
            - "BTC"
            - "EURtoBTC"

    net.telepay.exchanges.EURtoPLN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "EUR"
            - "PLN"
            - "EURtoPLN"

    net.telepay.exchanges.EURtoFAC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "EUR"
            - "FAC"
            - "EURtoFAC"

    net.telepay.exchanges.EURtoUSD.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "EUR"
            - "USD"
            - "EURtoUSD"

    net.telepay.exchanges.EURtoMXN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "EUR"
            - "MXN"
            - "EURtoMXN"

    net.telepay.exchanges.EURtoFAIRP.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "EUR"
            - "FAIRP"
            - "EURtoFAIRP"


    net.telepay.exchanges.FACtoBTC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAC"
            - "BTC"
            - "FACtoBTC"

    net.telepay.exchanges.FACtoPLN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAC"
            - "PLN"
            - "FACtoPLN"

    net.telepay.exchanges.FACtoEUR.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAC"
            - "EUR"
            - "FACtoEUR"

    net.telepay.exchanges.FACtoUSD.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAC"
            - "USD"
            - "FACtoUSD"

    net.telepay.exchanges.FACtoMXN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAC"
            - "MXN"
            - "FACtoMXN"

    net.telepay.exchanges.FACtoFAIRP.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAC"
            - "FAIRP"
            - "FACtoFAIRP"



    net.telepay.exchanges.PLNtoBTC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "PLN"
            - "BTC"
            - "PLNtoBTC"

    net.telepay.exchanges.PLNtoFAC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "PLN"
            - "FAC"
            - "PLNtoFAC"

    net.telepay.exchanges.PLNtoEUR.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "PLN"
            - "EUR"
            - "PLNtoEUR"

    net.telepay.exchanges.PLNtoUSD.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "PLN"
            - "USD"
            - "PLNtoUSD"

    net.telepay.exchanges.PLNtoMXN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "PLN"
            - "MXN"
            - "PLNtoMXN"

    net.telepay.exchanges.PLNtoFAIRP.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "PLN"
            - "FAIRP"
            - "PLNtoFAIRP"



    net.telepay.exchanges.USDtoBTC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "USD"
            - "BTC"
            - "USDtoBTC"

    net.telepay.exchanges.USDtoFAC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "USD"
            - "FAC"
            - "USDtoFAC"

    net.telepay.exchanges.USDtoEUR.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "USD"
            - "EUR"
            - "USDtoEUR"

    net.telepay.exchanges.USDtoPLN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "USD"
            - "PLN"
            - "USDtoPLN"

    net.telepay.exchanges.USDtoMXN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "USD"
            - "MXN"
            - "USDtoMXN"

    net.telepay.exchanges.USDtoFAIRP.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "USD"
            - "FAIRP"
            - "USDtoFAIRP"




    net.telepay.exchanges.MXNtoBTC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "MXN"
            - "BTC"
            - "MXNtoBTC"

    net.telepay.exchanges.MXNtoFAC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "MXN"
            - "FAC"
            - "MXNtoFAC"

    net.telepay.exchanges.MXNtoEUR.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "MXN"
            - "EUR"
            - "MXNtoEUR"

    net.telepay.exchanges.MXNtoPLN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "MXN"
            - "PLN"
            - "MXNtoPLN"

    net.telepay.exchanges.MXNtoUSD.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "MXN"
            - "USD"
            - "MXNtoUSD"

    net.telepay.exchanges.MXNtoFAIRP.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "MXN"
            - "FAIRP"
            - "MXNtoFAIRP"


    net.telepay.exchanges.FAIRPtoBTC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAIRP"
            - "BTC"
            - "FAIRPtoBTC"

    net.telepay.exchanges.FAIRPtoFAC.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAIRP"
            - "FAC"
            - "FAIRPtoBTC"

    net.telepay.exchanges.FAIRPtoEUR.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAIRP"
            - "EUR"
            - "FAIRPtoBTC"

    net.telepay.exchanges.FAIRPtoPLN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAIRP"
            - "PLN"
            - "FAIRPtoPLN"

    net.telepay.exchanges.FAIRPtoUSD.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAIRP"
            - "USD"
            - "FAIRPtoUSD"

    net.telepay.exchanges.FAIRPtoMXN.v1:
        class: Telepay\FinancialApiBundle\DependencyInjection\Transactions\Exchange
        arguments:
            - "FAIRP"
            - "MXN"
            - "FAIRPtoEUR"

