services:

    net.telepay.wallets:
        class: Telepay\FinancialApiBundle\Financial\ObjectRegister
        arguments:
            - "@net.telepay.wallet.fullnode.rec"

    net.telepay.wallet.fullnode.rec:
        class: Telepay\FinancialApiBundle\Financial\Wallet\FullNodeWallet
        arguments:
            - "@net.telepay.driver.easybitcoin.rec"
            - "REC"
            - '[]'
            - '[]'
