

super_admin_transaction_list:
    pattern:  /admin/v1/transaction/list
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\TransactionsController::listAction }
    requirements:
        _method: GET

super_admin_transaction_search:
    pattern:  /admin/v1/transaction/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\TransactionsController::findAction }
    requirements:
        _method: GET

system_last50transactions_index:
    pattern:  /system/v1/last50
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\System\ActivityController::last50Transactions }
    requirements:
        _method: GET


admin_companies_super_update:
    pattern:  /admin/v1/companies/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\CompaniesController::updateAction }
    requirements:
        _method: PUT

admin_companies_super_delete:
    pattern:  /admin/v1/companies/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\CompaniesController::deleteAction }
    requirements:
        _method: DELETE

admin_company_read:
    pattern:  /admin/v1/company/{id}/read
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\CompaniesController::showAction }
    requirements:
        _method: GET

####################  USER  ########################
admin_user_read:
    pattern:  /admin/v1/user/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::showAction }
    requirements:
        _method: GET

admin_users_update:
    pattern:  /admin/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::updateAction }
    requirements:
        _method: PUT
        id: "[0-9]+"
        name: "string"
        email: "email"
        password: "string"

admin_user_active:
    pattern:  /admin/v1/activeuser/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::activateAction, _format: ~ }
    requirements:
        _method: POST
        id: "[0-9]+"

admin_user_deactive:
    pattern:  /admin/v1/deactiveuser/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::deactivateAction, _format: ~ }
    requirements:
        _method: POST
        id: "[0-9]+"

admin_users_delete:
    pattern:  /admin/v1/users/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::deleteAction, _format: ~ }
    requirements:
        _method: DELETE
        id: "[0-9]+"

admin_users_delete_by_name:
    pattern:  /admin/v1/users/name/{username}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::deleteByNameAction, _format: ~ }
    requirements:
        _method: DELETE
        username: "string"

admin_user_update_kyc:
    pattern:  /admin/v1/user/{id}/kyc
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::updateKYCAction }
    requirements:
        _method: PUT

admin_user_update_phone:
    pattern:  /admin/v1/user/{id}/phone
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::updatePhoneAction }
    requirements:
        _method: PUT

admin_user_actions:
    pattern:  /admin/v1/user/{id}/{action}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::userActionsAction }
    requirements:
        _method: PUT

admin_groups_delete_users:
    pattern:  /admin/v1/groups/{group_id}/{user_id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\UsersController::deleteFromGroupAction, _format: ~ }
    requirements:
        _method: DELETE
        group_id: "[0-9]+"
        user_id: "[0-9]+"

##################### MAP ############################

map_visibility:
    pattern:  /admin/v1/map/visibility/{account_id}
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Management\Company\MapController::setVisibility }
    requirements:
        _method: PUT


admin_map_search:
    pattern: /admin/v1/map/search
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Management\Company\MapController::adminSearchV2 }
    requirements:
        _method: GET


admin_kyc_get_uploaded_files_by_user:
    pattern:  /admin/v1/kyc/uploads/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\KYCController::getUploadedFiles }
    requirements:
        _method: GET

admin_kyc_upload_file:
    pattern:  /admin/v1/kyc/file/{tag}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\KYCController::uploadFile }
    requirements:
        _method: POST

admin_kyc_delete_file:
    pattern:  /admin/v1/kyc/file/{tag}/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\KYCController::deleteFile }
    requirements:
        _method: DELETE


admin_kyc_lemon_create_account:
    pattern:  /admin/v1/kyc/lemon/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\KYCController::createLemonAccountAction }
    requirements:
        _method: POST


admin_kyc_lemon_newId_account:
    pattern:  /admin/v1/kyc/lemon_id
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\KYCController::newLemonIdAction }
    requirements:
        _method: POST



##################### ADMIN / DELEGATE CHANGE ############################

admin_index_delegate_change:
    pattern:  /admin/v1/delegated_changes
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeController::indexAction }
    requirements:
        _method: GET

admin_create_delegate_change:
    pattern:  /admin/v1/delegated_changes
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeController::createAction }
    requirements:
        _method: POST

admin_show_delegate_change:
    pattern:  /admin/v1/delegated_changes/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeController::showAction }
    requirements:
        _method: GET

admin_update_delegate_change:
    pattern:  /admin/v1/delegated_changes/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeController::updateAction }
    requirements:
        _method: PUT

admin_delete_delegate_change:
    pattern:  /admin/v1/delegated_changes/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeController::deleteAction }
    requirements:
        _method: DELETE


##################### ADMIN / DELEGATE CHANGE DATA ############################

admin_index_delegate_change_data:
    pattern:  /admin/v1/delegated_change_data
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeDataController::indexAction }
    requirements:
        _method: GET

admin_create_delegate_change_data:
    pattern:  /admin/v1/delegated_change_data
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeDataController::createAction }
    requirements:
        _method: POST

admin_show_delegate_change_data:
    pattern:  /admin/v1/delegated_change_data/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeDataController::showAction }
    requirements:
        _method: GET

admin_update_delegate_change_data:
    pattern:  /admin/v1/delegated_change_data/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeDataController::updateAction }
    requirements:
        _method: PUT

admin_delete_delegate_change_data:
    pattern:  /admin/v1/delegated_change_data/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeDataController::deleteAction }
    requirements:
        _method: DELETE

admin_create_delegate_change_data_from_csv:
    pattern:  /admin/v1/delegated_change_data/load_csv
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\DelegatedChangeDataController::loadCsvAction }
    requirements:
        _method: POST

##################### MASTER ACCOUNT WITHDRAWAL CONFIRMATION ############################

withdrawal_token_validation:
    pattern: /withdrawal/v1/{token}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Admin\SpecialActionsController::withdrawalAction }
    requirements:
        _method: GET