##################### COMPANY ACCOUNT ############################
account_update:
    pattern: /account/{account_id}/v1/profile
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\AccountController::updateAction }
    requirements:
        _method: PUT
        account_id: "[a-z0-9_]+"

fixed_location_update:
    pattern: /account/{account_id}/v1/location
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\AccountController::updateLocationAction }
    requirements:
        _method: PUT
        account_id: "[a-z0-9_]+"

company_set_comapny_image:
    pattern:  /company/v1/account/{account_id}/image
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\AccountController::setImage }
    requirements:
        _method: PUT

##company_set_user_manager:
##    pattern:  /company/v1/account/kyc/admin/{id}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\AccountController::setAdmin }
##    requirements:
##        _method: PUT

##company_kyc_upload_file:
##    pattern:  /company/v1/account/kyc/upload
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\KYCController::uploadFile }
##    requirements:
##        _method: POST

##company_kyc_get_uploaded_file:
##    pattern:  /company/v1/account/kyc/upload
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\KYCController::getUploadedFiles }
##    requirements:
##        _method: GET

##company_kyc_request_validation:
##    pattern:  /company/v1/account/kyc/validation
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\KYCController::requestValidation }
##    requirements:
##        _method: PUT

##################### COMPANY ############################

##company_update_tier:
##    pattern:  /company/v1/tier/{company_id}/{tier}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\SpecialActionsController::changeTier }
##    requirements:
##        _method: PUT


##company_update_transaction:
##    pattern:  /company/v1/wallet/transaction/{id}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\WalletController::updateAction }
##    requirements:
##        _method: PUT


######################## COMPANY SCHEDULED ########################

##scheduled_list:
##    pattern:  /company/v1/scheduled
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ScheduledController::indexAction }
##    requirements:
##        _method: GET

##scheduled_create:
##    pattern:  /company/v1/scheduled
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ScheduledController::createAction }
##    requirements:
##        _method: POST

##scheduled_update:
##    pattern:  /company/v1/scheduled/{id}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ScheduledController::updateAction }
##    requirements:
##        _method: PUT

##scheduled_delete:
##    pattern:  /company/v1/scheduled/{id}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ScheduledController::deleteAction }
##    requirements:
##        _method: DELETE

######################## COMPANY NFC ########################

##create_nfc_card:
##    pattern:  /company/v1/nfc_card
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\NFCController::registerCard }
##    requirements:
##        _method: POST

##read_balance_nfc_card:
##    pattern:  /company/v1/nfc_card/balance
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\NFCController::readBalanceNFCCard }
##    requirements:
##        _method: POST

##recharge_nfc_card:
##    pattern:  /company/v1/nfc_card/{company_id}/recharge
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\NFCController::rechargeCard }
##    requirements:
##        _method: POST

##update_nfc_card_from_app:
##    pattern:  /company/v1/nfc_card
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\NFCController::updateCard }
##    requirements:
##        _method: PUT

##index_nfc_card:
##    pattern:  /company/v1/nfc_cards
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\NFCController::indexCards }
##    requirements:
##        _method: GET

##update_nfc_card:
##    pattern:  /company/v1/nfc_card/{id}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\NFCController::updateCardFromCompany }
##    requirements:
##        _method: PUT


######################## CREDIT CARD ########################

create_credit_card:
    pattern:  /company/v1/credit_card
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\CreditCardController::registerCard }
    requirements:
        _method: POST

index_credit_card:
    pattern:  /company/v1/credit_card
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\CreditCardController::indexCards }
    requirements:
        _method: GET

update_credit_card:
    pattern:  /company/v1/credit_card/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\CreditCardController::updateCardFromCompany }
    requirements:
        _method: PUT

delete_credit_card:
    pattern:  /company/v1/credit_card/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\CreditCardController::deleteAction }
    requirements:
        _method: DELETE

######################## BANK ACCOUNT ########################

create_bank_account:
    pattern:  /company/v1/bank_account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\BankAccountController::registerAccount }
    requirements:
        _method: POST

index_bank_account:
    pattern:  /company/v1/bank_account
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\BankAccountController::indexAccounts }
    requirements:
        _method: GET

update_bank_account:
    pattern:  /company/v1/bank_account/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\BankAccountController::updateAccountFromCompany }
    requirements:
        _method: PUT

delete_bank_account:
    pattern:  /company/v1/bank_account/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\BankAccountController::deleteAction }
    requirements:
        _method: DELETE


######################## OFFERS ########################

create_offer:
    pattern:  /company/v1/offer
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\OfferController::registerOffer }
    requirements:
        _method: POST

index_offer:
    pattern:  /company/v1/offer
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\OfferController::indexOffers }
    requirements:
        _method: GET

update_offer:
    pattern:  /company/v1/offer/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\OfferController::updateOfferFromCompany }
    requirements:
        _method: PUT

delete_offer:
    pattern:  /company/v1/offer/{id}
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\OfferController::deleteAction }
    requirements:
        _method: DELETE

######################## Products ########################

list_all_categories:
    pattern:  /company/v1/list_categories
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ProductController::listAllAction }
    requirements:
        _method: GET

index_products:
    pattern:  /company/v1/products
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ProductController::indexAction }
    requirements:
        _method: GET

set_products:
    pattern:  /company/v1/products
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ProductController::setAction }
    requirements:
        _method: PUT

set_category:
    pattern:  /company/v1/category
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\ProductController::setCategoryAction }
    requirements:
        _method: PUT

###################   COMPANY WALLET #################
company_wallet:
    pattern:  /company/{company_id}/v1/wallets
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\WalletController::read }
    requirements:
        _method: GET

##company_wallet_do_exchange:
##    pattern:  /company/{company_id}/v1/wallet/exchange
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\WalletController::currencyExchange, _format: ~ }
##    requirements:
##        _method: POST

company_wallet_transactions:
    pattern:  /company/{company_id}/v1/wallet/transactions
    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\WalletController::walletTransactions }
    requirements:
        _method: GET

###################   COMPANY SETTINGS #################
##company_read_settings:
##    pattern: /company/v1/{company_id}/settings
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\SettingsController::readSettings }
##    requirements:
##        _method: GET

##company_update_settings:
##    pattern: /company/v1/{company_id}/settings
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Company\SettingsController::updateSettings }
##    requirements:
##        _method: PUT

##################     COMPANY METHODS     ###############
##company_method_read:
##    pattern:  /company/{id}/v1/methods/{method}
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Integrator\MethodsController::read }
##    requirements:
##        _method: GET

##company_method_index:
##    pattern:  /company/{id}/v1/methods
##    defaults: { _controller: Telepay\FinancialApiBundle\Controller\Management\Integrator\MethodsController::index }
##    requirements:
##        _method: GET


#################     ACCOUNT FEES    ######################
##company_index_fees:
##    pattern: /account/{account_id}/v1/fees
##    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Management\Company\WalletController::indexFees }
##    requirements:
##        _method: GET

##company_show_fee:
##    pattern: /account/{account_id}/v1/fees/{method}
##    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Management\Company\WalletController::showFees }
##    requirements:
##        _method: GET


##################### MAP ############################
map_list:
    pattern: /map/v1/list
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Management\Company\MapController::ListAction }
    requirements:
        _method: GET

map_search:
    pattern: /map/v1/search
    defaults: {_controller: Telepay\FinancialApiBundle\Controller\Management\Company\MapController::SearchAction }
    requirements:
        _method: GET

